//go:build ignore

// Command gen stamps version_gen.go from version.txt, so the vendored SDL's
// stash-box release tag is available as a programmatic constant. It is invoked
// by `go generate ./schema` (see schema.go) and by schema/refresh.sh.
package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	raw, err := os.ReadFile("version.txt")
	if err != nil {
		fmt.Fprintln(os.Stderr, "stamp:", err)
		os.Exit(1)
	}
	version := strings.TrimSpace(string(raw))
	if version == "" {
		fmt.Fprintln(os.Stderr, "stamp: version.txt is empty")
		os.Exit(1)
	}

	const tmpl = `// Code generated by go run gen.go; DO NOT EDIT.

package schema

// SchemaVersion is the stash-box release tag of the SDL vendored in this directory.
const SchemaVersion = %q
`
	if err := os.WriteFile("version_gen.go", []byte(fmt.Sprintf(tmpl, version)), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "stamp:", err)
		os.Exit(1)
	}
}
