// Package stashbox is a Go client library for the stash-box GraphQL API
// (StashDB and any other stash-box instance). It wraps the typed operations
// generated by genqlient with a configured transport, a typed error model, and
// a bounded fan-out helper for batch work.
//
// stash-box is a read-only target for this client: the generated surface is
// query-only (the Mutation root is stripped before code generation, see
// generate.go), there are no subscriptions, and no operation sends an upload.
// The client therefore carries only an HTTP POST transport — no WebSocket layer
// and no multipart path.
//
// A [Client] is created with [NewClient] and configured through [Option] values
// or the STASHBOX_URL and STASHBOX_API_KEY environment variables. Pass
// [Client.GraphQL] to the generated operation functions:
//
//	c, err := stashbox.NewClient(stashbox.WithURL("https://stashdb.org"))
//	resp, err := stashbox.Version(ctx, c.GraphQL())
package stashbox

import (
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// defaultTimeout bounds requests made through the default *http.Client. A
// caller-supplied client (via [WithHTTPClient]) keeps its own timeout instead.
const defaultTimeout = 30 * time.Second

// Client is a configured handle to a stash-box GraphQL server. It carries the
// normalised endpoint, the HTTP transport that injects the ApiKey header, and a
// logger. It is safe for concurrent use; the underlying *http.Client is shared.
type Client struct {
	endpoint   string
	apiKey     string
	httpClient *http.Client
	gql        graphql.Client
	logger     *slog.Logger
}

// NewClient builds a [Client] from the given options and the environment.
//
// Configuration precedence for each setting is: an explicit option, then the
// environment variable (STASHBOX_URL, STASHBOX_API_KEY), then a default. The
// URL is required; if it resolves to empty, NewClient returns [ErrNoURL]. The
// API key is optional, since some instances expose read access unauthenticated.
//
// The URL is normalised to address the GraphQL endpoint (see [Client.Endpoint]):
// posting GraphQL to a stash-box base URL returns the single-page-app HTML, so a
// bare host or root path gains a /graphql suffix. The ApiKey header is injected
// by wrapping the transport's RoundTripper, so a caller-supplied client from
// [WithHTTPClient] keeps its own timeout and settings while still authenticating.
func NewClient(opts ...Option) (*Client, error) {
	var cfg config
	for _, opt := range opts {
		opt(&cfg)
	}

	rawURL := cfg.rawURL
	if rawURL == "" {
		rawURL = os.Getenv("STASHBOX_URL")
	}
	if rawURL == "" {
		return nil, ErrNoURL
	}

	endpoint, err := normaliseURL(rawURL)
	if err != nil {
		return nil, err
	}

	apiKey := cfg.apiKey
	if !cfg.apiKeySet {
		apiKey = os.Getenv("STASHBOX_API_KEY")
	}

	httpClient := buildHTTPClient(cfg, apiKey)

	logger := cfg.logger
	if logger == nil {
		logger = slog.Default()
	}

	return &Client{
		endpoint:   endpoint,
		apiKey:     apiKey,
		httpClient: httpClient,
		gql:        graphql.NewClient(endpoint, httpClient),
		logger:     logger,
	}, nil
}

// buildHTTPClient produces the *http.Client used for requests. A
// caller-supplied client keeps its own timeout and only has its transport
// wrapped to inject the key; otherwise a default client with a bounded timeout
// is created. The key is injected only when non-empty.
//
// A caller-supplied client (from [WithHTTPClient]) is shallow-copied: only its
// Transport is replaced (with a key-injecting wrapper) and its Timeout is
// preserved. Remaining fields — Jar and CheckRedirect — are copied by value
// from the original, so any non-nil CookieJar or CheckRedirect func is *shared*
// (the same underlying value), not cloned. Callers relying on isolated cookie
// state should pass a dedicated client.
func buildHTTPClient(cfg config, apiKey string) *http.Client {
	if cfg.httpClient != nil {
		c := *cfg.httpClient
		c.Transport = apiKeyTransport(c.Transport, apiKey)
		return &c
	}

	timeout := cfg.timeout
	if timeout == 0 {
		timeout = defaultTimeout
	}
	return &http.Client{
		Timeout:   timeout,
		Transport: apiKeyTransport(http.DefaultTransport, apiKey),
	}
}

// apiKeyTransport wraps base with a RoundTripper that adds the ApiKey header.
// When key is empty the base transport is returned unwrapped, so no header is
// sent. A nil base falls back to http.DefaultTransport.
func apiKeyTransport(base http.RoundTripper, key string) http.RoundTripper {
	if key == "" {
		return base
	}
	if base == nil {
		base = http.DefaultTransport
	}
	return &authRoundTripper{base: base, apiKey: key}
}

// authRoundTripper injects the stash-box ApiKey header on every request. It
// clones the request before mutating headers, as the [http.RoundTripper]
// contract requires.
type authRoundTripper struct {
	base   http.RoundTripper
	apiKey string
}

// RoundTrip adds the ApiKey header to a clone of req and delegates to the base
// transport.
func (t *authRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
	clone := req.Clone(req.Context())
	clone.Header.Set("ApiKey", t.apiKey)
	return t.base.RoundTrip(clone)
}

// normaliseURL parses rawURL and returns the GraphQL endpoint. A bare host or a
// root path gains a /graphql suffix; a path that already ends in /graphql is
// kept. This matches the stash-box contract: posting GraphQL to the base UI URL
// returns the SPA's HTML, so the endpoint must address <base>/graphql.
//
// Only http and https are accepted: genqlient's HTTP client POSTs to the
// endpoint, so a missing scheme, a missing host, or any non-HTTP scheme is
// rejected. Surrounding whitespace is trimmed before parsing so a stray space
// copied into STASHBOX_URL or a .env file does not error. Query strings and
// fragments are meaningless for a GraphQL POST, so they are dropped.
func normaliseURL(rawURL string) (endpoint string, err error) {
	rawURL = strings.TrimSpace(rawURL)

	u, err := url.Parse(rawURL)
	if err != nil {
		// url.Parse's own error message embeds the raw URL verbatim, so wrapping
		// it with %w would re-leak any query secret that redactURL stripped from
		// the %q copy. Redact the wrapped error's text too; the typed cause stays
		// reachable via errors.As (url.Parse returns a *url.Error).
		var pathErr *url.Error
		if errors.As(err, &pathErr) {
			pathErr.URL = redactURL(pathErr.URL)
		}
		return "", fmt.Errorf("stashbox: parsing URL %q: %w", redactURL(rawURL), err)
	}
	if u.Scheme == "" || u.Host == "" {
		return "", fmt.Errorf("stashbox: URL %q must include a scheme and host (e.g. https://stashdb.org)", redactURL(rawURL))
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return "", fmt.Errorf("stashbox: URL %q has unsupported scheme %q (want http or https)", redactURL(rawURL), u.Scheme)
	}

	path := strings.TrimRight(u.Path, "/")
	switch {
	case path == "":
		path = "/graphql"
	case strings.HasSuffix(path, "/graphql"):
		// Already targets the endpoint; leave it.
	default:
		path += "/graphql"
	}
	u.Path = path

	// Query and fragment have no meaning for a GraphQL POST; drop them.
	u.RawQuery = ""
	u.Fragment = ""

	return u.String(), nil
}

// GraphQL returns the genqlient client to pass to generated operation
// functions, for example stashbox.Version(ctx, c.GraphQL()).
func (c *Client) GraphQL() graphql.Client { return c.gql }

// Endpoint returns the normalised GraphQL endpoint, of the form
// http(s)://host[:port]/path/graphql.
func (c *Client) Endpoint() string { return c.endpoint }

// HTTPClient returns the underlying *http.Client, whose transport injects the
// ApiKey header.
func (c *Client) HTTPClient() *http.Client { return c.httpClient }

// APIKey returns the configured API key.
func (c *Client) APIKey() string { return c.apiKey }

// Logger returns the diagnostics logger. It is never nil; an unconfigured
// client uses slog.Default.
func (c *Client) Logger() *slog.Logger { return c.logger }

// LogValue implements [slog.LogValuer] so a Client can be logged as a structured
// value with its secrets redacted. The API key is never written to logs, and the
// endpoint is run through [redactURL] before logging — masking both a
// user:password@host userinfo component and any apikey/token query secret — so a
// credential embedded in STASHBOX_URL cannot leak. (A normalised endpoint drops
// its query string, but redacting defensively costs nothing.)
func (c *Client) LogValue() slog.Value {
	attrs := []slog.Attr{
		slog.String("endpoint", redactURL(c.endpoint)),
	}
	if c.apiKey != "" {
		attrs = append(attrs, slog.String("api_key", "REDACTED"))
	}
	return slog.GroupValue(attrs...)
}
