// Code generated by genops; DO NOT EDIT.

package main

import "github.com/lightning-rider-999/go-stashbox/stashbox"

// generatedCommands is the full operation table, one spec per stash-box
// root field, sorted by OpName. buildRootCommand assembles these into the
// cobra tree. Query is the genqlient operation const, so the query text
// lives in exactly one place. Every entry is a query: go-stashbox is a
// read-only client and the generator is fed a query-only schema view.
var generatedCommands = []commandSpec{
	{Path: []string{"draft", "get"}, OpName: "FindDraft", Query: stashbox.FindDraft_Operation, Kind: "query", InputType: "", ReturnType: "Draft", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"draft", "list"}, OpName: "FindDrafts", Query: stashbox.FindDrafts_Operation, Kind: "query", InputType: "", ReturnType: "Draft", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"edit", "get"}, OpName: "FindEdit", Query: stashbox.FindEdit_Operation, Kind: "query", InputType: "", ReturnType: "Edit", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"performer", "get"}, OpName: "FindPerformer", Query: stashbox.FindPerformer_Operation, Kind: "query", InputType: "", ReturnType: "Performer", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"scene", "get"}, OpName: "FindScene", Query: stashbox.FindScene_Operation, Kind: "query", InputType: "", ReturnType: "Scene", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"scene", "list-by-fingerprints"}, OpName: "FindScenesBySceneFingerprints", Query: stashbox.FindScenesBySceneFingerprints_Operation, Kind: "query", InputType: "", ReturnType: "Scene", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"site", "get"}, OpName: "FindSite", Query: stashbox.FindSite_Operation, Kind: "query", InputType: "", ReturnType: "Site", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"site-category", "get"}, OpName: "FindSiteCategory", Query: stashbox.FindSiteCategory_Operation, Kind: "query", InputType: "", ReturnType: "SiteCategory", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"studio", "get"}, OpName: "FindStudio", Query: stashbox.FindStudio_Operation, Kind: "query", InputType: "", ReturnType: "Studio", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"tag", "get"}, OpName: "FindTag", Query: stashbox.FindTag_Operation, Kind: "query", InputType: "", ReturnType: "Tag", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"tag-category", "get"}, OpName: "FindTagCategory", Query: stashbox.FindTagCategory_Operation, Kind: "query", InputType: "", ReturnType: "TagCategory", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"tag", "get-by-alias"}, OpName: "FindTagOrAlias", Query: stashbox.FindTagOrAlias_Operation, Kind: "query", InputType: "", ReturnType: "Tag", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"user", "get"}, OpName: "FindUser", Query: stashbox.FindUser_Operation, Kind: "query", InputType: "", ReturnType: "User", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"scene", "fingerprint-clusters"}, OpName: "FingerprintClusters", Query: stashbox.FingerprintClusters_Operation, Kind: "query", InputType: "FingerprintClustersInput", ReturnType: "FingerprintClustersResult", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"config", "get"}, OpName: "GetConfig", Query: stashbox.GetConfig_Operation, Kind: "query", InputType: "", ReturnType: "StashBoxConfig", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"notification", "unread-count"}, OpName: "GetUnreadNotificationCount", Query: stashbox.GetUnreadNotificationCount_Operation, Kind: "query", InputType: "", ReturnType: "UnreadNotificationCount", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"user", "me"}, OpName: "Me", Query: stashbox.Me_Operation, Kind: "query", InputType: "", ReturnType: "User", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"edit", "query"}, OpName: "QueryEdits", Query: stashbox.QueryEdits_Operation, Kind: "query", InputType: "EditQueryInput", ReturnType: "QueryEditsResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"performer", "query-existing"}, OpName: "QueryExistingPerformer", Query: stashbox.QueryExistingPerformer_Operation, Kind: "query", InputType: "QueryExistingPerformerInput", ReturnType: "QueryExistingPerformerResult", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"scene", "query-existing"}, OpName: "QueryExistingScene", Query: stashbox.QueryExistingScene_Operation, Kind: "query", InputType: "QueryExistingSceneInput", ReturnType: "QueryExistingSceneResult", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"mod-audit", "query"}, OpName: "QueryModAudits", Query: stashbox.QueryModAudits_Operation, Kind: "query", InputType: "ModAuditQueryInput", ReturnType: "QueryModAuditsResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"notification", "query"}, OpName: "QueryNotifications", Query: stashbox.QueryNotifications_Operation, Kind: "query", InputType: "QueryNotificationsInput", ReturnType: "QueryNotificationsResult", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"performer", "query"}, OpName: "QueryPerformers", Query: stashbox.QueryPerformers_Operation, Kind: "query", InputType: "PerformerQueryInput", ReturnType: "QueryPerformersResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"scene", "query"}, OpName: "QueryScenes", Query: stashbox.QueryScenes_Operation, Kind: "query", InputType: "SceneQueryInput", ReturnType: "QueryScenesResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"site-category", "query"}, OpName: "QuerySiteCategories", Query: stashbox.QuerySiteCategories_Operation, Kind: "query", InputType: "", ReturnType: "QuerySiteCategoriesResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"site", "query"}, OpName: "QuerySites", Query: stashbox.QuerySites_Operation, Kind: "query", InputType: "", ReturnType: "QuerySitesResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"studio", "query"}, OpName: "QueryStudios", Query: stashbox.QueryStudios_Operation, Kind: "query", InputType: "StudioQueryInput", ReturnType: "QueryStudiosResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"tag-category", "query"}, OpName: "QueryTagCategories", Query: stashbox.QueryTagCategories_Operation, Kind: "query", InputType: "", ReturnType: "QueryTagCategoriesResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"tag", "query"}, OpName: "QueryTags", Query: stashbox.QueryTags_Operation, Kind: "query", InputType: "TagQueryInput", ReturnType: "QueryTagsResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"user", "query"}, OpName: "QueryUsers", Query: stashbox.QueryUsers_Operation, Kind: "query", InputType: "UserQueryInput", ReturnType: "QueryUsersResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"performer", "search-one"}, OpName: "SearchPerformer", Query: stashbox.SearchPerformer_Operation, Kind: "query", InputType: "", ReturnType: "Performer", Destructive: false, JobReturning: false, Deprecated: true},
	{Path: []string{"performer", "search"}, OpName: "SearchPerformers", Query: stashbox.SearchPerformers_Operation, Kind: "query", InputType: "", ReturnType: "QueryPerformersResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"scene", "search-one"}, OpName: "SearchScene", Query: stashbox.SearchScene_Operation, Kind: "query", InputType: "", ReturnType: "Scene", Destructive: false, JobReturning: false, Deprecated: true},
	{Path: []string{"scene", "search"}, OpName: "SearchScenes", Query: stashbox.SearchScenes_Operation, Kind: "query", InputType: "", ReturnType: "QueryScenesResultType", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"studio", "search"}, OpName: "SearchStudio", Query: stashbox.SearchStudio_Operation, Kind: "query", InputType: "", ReturnType: "Studio", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"tag", "search"}, OpName: "SearchTag", Query: stashbox.SearchTag_Operation, Kind: "query", InputType: "", ReturnType: "Tag", Destructive: false, JobReturning: false, Deprecated: false},
	{Path: []string{"misc", "version"}, OpName: "Version", Query: stashbox.Version_Operation, Kind: "query", InputType: "", ReturnType: "Version", Destructive: false, JobReturning: false, Deprecated: false},
}
